theme: jekyll-theme-cayman
title: THE YYYY（ザ・イヤーズ）
plugins:
 - jekyll-sitemap
google_analytics: G-H1234VX5NE
gems:
<<<<<<< Updated upstream
  - jekyll-sitemap
=======
  - jekyll-sitemap
>>>>>>> Stashed changes
